[2024-06-24T10:12:46.016+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T10:12:46.036+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.processing_tasks.inject_data_kyiv scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-24T10:12:46.046+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.processing_tasks.inject_data_kyiv scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-24T10:12:46.046+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-24T10:12:46.066+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): processing_tasks.inject_data_kyiv> on 2024-06-23 00:00:00+00:00
[2024-06-24T10:12:46.076+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=136) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T10:12:46.078+0000] {standard_task_runner.py:63} INFO - Started process 140 to run task
[2024-06-24T10:12:46.078+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'processing_tasks.inject_data_kyiv', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpieo9zdma']
[2024-06-24T10:12:46.082+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask processing_tasks.inject_data_kyiv
[2024-06-24T10:12:46.142+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.processing_tasks.inject_data_kyiv scheduled__2024-06-23T00:00:00+00:00 [running]> on host afc8096e8b86
[2024-06-24T10:12:46.286+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='processing_tasks.inject_data_kyiv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-23T00:00:00+00:00'
[2024-06-24T10:12:46.289+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T10:12:46.290+0000] {sql.py:276} INFO - Executing: 
            INSERT INTO measures (timestamp, temp, city) VALUES (to_timestamp(1719223721), 293.9, 'Kyiv');
            
[2024-06-24T10:12:46.299+0000] {base.py:84} INFO - Using connection ID 'ps_db_conn' for task execution.
[2024-06-24T10:12:46.310+0000] {base.py:84} INFO - Using connection ID 'ps_db_conn' for task execution.
[2024-06-24T10:12:46.314+0000] {sql.py:487} INFO - Running statement: 
            INSERT INTO measures (timestamp, temp, city) VALUES (to_timestamp(1719223721), 293.9, 'Kyiv');
            , parameters: None
[2024-06-24T10:12:46.315+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-24T10:12:46.318+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T10:12:46.328+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=processing_tasks.inject_data_kyiv, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20240624T101246, end_date=20240624T101246
[2024-06-24T10:12:46.373+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-24T10:12:46.393+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T10:12:46.396+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
